vulsio/go-cve-dictionary

- commands/server.go
I found a typo in `commands/server.go` . This pull request fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kotakanbe/go-cve-dictionary/12)
> fix typo: Sever -> Server

- README.md
- models/models.go
- nvd/nvd.go
- version/version.go
https://github.com/future-architect/vuls/pull/77
> Don't output Gorm's columns(ID, date) in JSON

- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- config/config.go
- db/db.go
- models/models.go
Added support to use MySQL as the back-end storage.  I have tested pulling CVE's and running a server to ensure that I can successfully store and read in data.
`./go-cve-dictionary fetchnvd -years -dbtype mysql -dbpath root:oswell@/vuls?parseTime=true 2016`
`./go-cve-dictionary server -dbtype mysql -dbpath root:oswell@/vuls?parseTime=true`
I opted to overload the "dbpath" flag for the MySQL connection string as the naming still sort of makes sense and it required less changes.
> Add support for MySQL as a DB storage back-end

- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- glide.lock
- main.go
Corresponding to https://github.com/google/subcommands/pull/5.
- https://tip.golang.org/doc/go1.7#context
Currently, `go get github.com/kotakanbe/go-cve-dictionary` is failed. It's ok according to a latest README, but an old README is still referred, so I fixed it.
- https://github.com/kotakanbe/go-cve-dictionary/commit/683256b65f7f968df15a99f08054c08e4b597490#diff-04c6e90faac2675aa89e2176d2eec7d8L52
- http://dev.classmethod.jp/etc/vuls-security-install/
- https://blog.animereview.jp/vuls/
- http://qiita.com/sadayuki-matsuno/items/0bb8bb1689425bb9a21c
> Moved golang.org/x/net/context to context

- Makefile
go 1.6 has vet included.
- https://github.com/purpleidea/mgmt/pull/38
- http://stackoverflow.com/questions/37755531/cannot-install-vet-package-with-go-get
> go v1.7.1 or later
>> https://github.com/kotakanbe/go-cve-dictionary
go version is no problem.
> Remove vet

- db/db.go
- glide.lock
- glide.yaml
CRLF is used as a line feed code in titles, summaries in JVN which is a Japanese vulnerability database.
As it is, it will collapse at terminal display, so remove CR when inserting to DB.
> Remove CR(^M) in JVN (Vulnerability database in Japanese)

- commands/fetchnvd.go
- commands/server.go
Fix import error
```
go build -ldflags "-X 'main.version=v0.1.0' -X 'main.revision=1551cb5'" -o go-cve-dictionary main.go
commands/fetchnvd.go:10:2: cannot find package "github.com/future-architect/vuls/util" in any of:
/go/vuls/src/github.com/kotakanbe/go-cve-dictionary/vendor/github.com/future-architect/vuls/util (vendor tree)
/usr/local/Cellar/go/1.7.4_2/libexec/src/github.com/future-architect/vuls/util (from $GOROOT)
/go/vuls/src/github.com/future-architect/vuls/util (from $GOPATH)
make: *** [build] Error 1
```
> Fix package import

- Gopkg.lock
- README.md
- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- db/db.go
- db/rdb.go
- db/redis.go
- models/models.go
- server/server.go
I added the dbtype of redis.
I tested this as follow.
1. prepare docker-compose.yml
```
$ vim docker-compose.yml
version: "3"
services:
redis:
image: redis
ports:
- "6379:6379"
redisCommander:
image: tenstartups/redis-commander
command: --redis-host redis
links:
- redis:redis
ports:
- "8081:8081"
```
2. run redis docker with GUI
```
$ docker-compose up -d
```
3. fetchjvn
```
$ go-cve-dictionary  fetchjvn  -last2y -debug  -dbtype redis -dbpath "redis://localhost/0"
```
4. fetchnvd
```
$ go-cve-dictionary  fetchnvd  -last2y -debug  -dbtype redis -dbpath "redis://localhost/0"
```
5. confirm the data
access to `localhost:8081`
- CVE
- ![2017-06-05 3 50 27](https://cloud.githubusercontent.com/assets/8997330/26764454/2d26155e-49a2-11e7-9cf9-78b2fa7773c3.png)
- CPE
- ![2017-06-05 3 53 …
> add redis as db back end

- db/db.go
- db/rdb.go
- db/redis.go
I add prefix("CVE#") into redis hash key because we can use the redis database as go-cvedictionary backend along with other dictionary(ex. ovaldictioanry)
> [BreakingChange] change redis keyname

- Gopkg.lock
- Gopkg.toml
- jvn/jvn.go
- log/log.go
- nvd/nvd.go
This errors occurred.
```
grouped write of manifest, lock and vendor: error while writing out vendor tree: error while exporting github.com/sirupsen/logrus: /var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/.gitignore already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/.travis.yml already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/CHANGELOG.md already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/LICENSE already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/README. …
```
> change logrus package name and update other package version

- Gopkg.lock
- README.md
- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- config/config.go
- db/rdb.go
- db/redis.go
- jvn/jvn.go
- log/log.go
- main.go
- nvd/nvd.go
1. add quiet option
2. change all output to stderr
3. add args environment
4. no output if not execute log.Initialize 
(when we used go-cve-dictionary's method without log.Initialize, panic occured.)
> add quiet option and args environment for AWS Lambda

- db/db.go
Fix a bug that did not insert an entry with multiple CVE-IDs in JVN>references
> fix: Insert JVN entries which have multiple CVE-IDs in references

- .gitignore
- .goreleaser.yml
- .travis.yml
After Travis is configured with the GitHub token, this will automatically publish binaries.
See https://github.com/future-architect/vuls/pull/460 and https://github.com/kotakanbe/go-cve-dictionary/pull/75#issuecomment-377140104
> Add goreleaser to distribute binaries

- README.md
- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/list.go
- commands/server.go
- log/log.go
add  log-json option
`go-cve-dictionary fetchjvn -last2y -log-json`
- stderr
```
{"lvl":"info","msg":"Fetching... https://jvndb.jvn.jp/ja/feed/checksum.txt","t":"2018-04-26T13:59:13.833838266+09:00"}
{"lvl":"info","msg":"Up to date: https://jvndb.jvn.jp/ja/rss/years/jvndb_2018.rdf","t":"2018-04-26T13:59:14.308656273+09:00"}
{"lvl":"info","msg":"Up to date: https://jvndb.jvn.jp/ja/rss/years/jvndb_2017.rdf","t":"2018-04-26T13:59:14.308785301+09:00"}
{"lvl":"info","msg":"Up to date: https://jvndb.jvn.jp/ja/rss/jvndb.rdf","t":"2018-04-26T13:59:14.30883456+09:00"}
{"lvl":"info","msg":"Up to date: https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf","t":"2018-04-26T13:59:14.308876084+09:00"}
{"lvl":"info","msg":"Already up to date","t":"2018-04-26T13:59:14.308917585+09:00"}
```
- logfile
``` …
```
> add log-json option

- db/rdb.go
I got the following error on `nvd-json` branch.
```
EROR[07-03|18:25:17] Failed to insert. dbpath: ~/src/github.com/kotakanbe/go-cve-dictionary/cve.sqlite3, err: database is locked
```
In the transaction, `tx` should be used.
> fix(rdb): use tx instead of r.conn

- models/models.go
An error occurred while fetching NVD feed with MySQL backend.
```
Error 1406: Data too long for column 'well_formed_name' at row 1
```
Change from Varcar fixed length type to text type.
> fix(db): chagne RDB column type to text

- GNUmakefile
- db/redis.go
Since the amount of data of cpe is enormous, we used useless memory space when cve information other than cpe is acquired, so we changed cpe's data separately from cve's data
> fix(db) separate cpe data from cve in redis

- README.md
Hello.
`CHANGELOG.md` was removed in 6f5010d237248c107fe5fa3c4f849c7426c9a02f.
This PR removed link to changelog on README.
> Remove CHANGELOG link already removed

- fetcher/nvd/json/nvd.go
```
`EROR[11-07|17:14:15] Failed to convert to model. cve: CVE-2014-5606, err: Error! cannot have unquoted ? embedded in formatted string.: Parse error`
```
```
struct { Vulnerable bool "json:\"vulnerable\""; Cpe23URI string "json:\"cpe23Uri\""; VersionStartExcluding string "json:\"versionStartExcluding\""; VersionStartIncluding string "json:\"versionStartIncluding\""; VersionEndExcluding string "json:\"versionEndExcluding\""; VersionEndIncluding string "json:\"versionEndIncluding\"" }{
Vulnerable:            true,
Cpe23URI:              "cpe:2.3:a:disney:where\\'s_my_perry?_free:1.5.1:*:*:*:*:android:*:*",
VersionStartExcluding: "",
VersionStartIncluding: "",
VersionEndExcluding:   "",
VersionEndIncluding:   "",
}
EROR[11-07|17:16:54] Failed to convert to model. cve: CVE-2014-5606, err: …
```
> fix(nvdjson): parse cpe of `disney android` in 2014 feed

- db/db.go
Also check vendor, product while matcing.
ex: 
in the current implementation, `cpe:/a:apache:struts:2.3.35` detects below CVEs.
https://nvd.nist.gov/vuln/detail/CVE-2016-3093
```
Vulnerable software and versions Switch to CPE 2.2
Configuration 1
AND
OR
cpe:2.3:a:ognl_project:ognl:*:*:*:*:*:*:*:*    versions up to (including) 3.0.11
OR
cpe:2.3:a:apache:struts:2.0.0:*:*:*:*:*:*:*
cpe:2.3:a:apache:struts:2.0.1:*:*:*:*:*:*:*
cpe:2.3:a:apache:struts:2.0.2:*:*:*:*:*:*:*
....
```
It will be detected incorrectly by matching a:ognl_project:ognl.
https://nvd.nist.gov/vuln/detail/CVE-2013-4316
> fix(cpe): fix cpe match false positive

- db/rdb.go
When a CVE information updated, the program deletes a old CVE infomation.
However, a parameter passed to the gorm.Delete function is a pointer of array of a cvss.
It don't have a primary key to delete.(Why? because it is a pointer of a array!)
Finaly, the gorm deletes all record in a table. ('delete from cvss2')
This will fix #114.
not fixed log
```
(/home/ubuntu/go/src/github.com/kotakanbe/go-cve-dictionary/db/rdb.go:495)
[2018-11-22 13:52:42]  [0.34ms]  SELECT * FROM "cve_details"  WHERE "cve_details"."deleted_at" IS NULL AND (("cve_details"."cve_id" = 'CVE-2017-3269')) ORDER BY "cve_details"."id" ASC LIMIT 1
[1 rows affected or returned ]
(/home/ubuntu/go/src/github.com/kotakanbe/go-cve-dictionary/db/rdb.go:510)
[2018-11-22 13:52:42]  [0.35ms]  SELECT * FROM "jvns"  WHERE …
```
> fix cvss2/cvss3 lost when update CVE info.

- db/db.go
- db/rdb.go
- db/redis.go
This creates an GetIdByCpeURI endpoint on the DB interface.
The rdb implementation splits the existing `GetByCpeURI` call into an `GetIdByCpeURI ` and the existing `GetMulti`. This reduces the duplication, while exposing intermediary data.
(I’m not sure if this is desired, but I found it useful for the tools I’m writing)
Fixes https://github.com/kotakanbe/go-cve-dictionary/issues/124
> Create GetIdByCpeURI endpoint

- server/server.go
This just adds an endpoint for the new functionality in https://github.com/kotakanbe/go-cve-dictionary/pull/126
> Add server route for GetCveIDsByCpeURI

- db/rdb.go
- fetcher/jvn/xml/jvn.go
- fetcher/nvd/json/nvd.go
- models/models.go
add a DB table to collect undetected alerts
You can check DB schema using `sqlite3`.
```
sqlite> .table
affects       cve_details   cvss3         env_cpes      nvd_jsons
certs         cvss2         cwes          feed_meta     nvd_xmls
cpes          cvss2_extras  descriptions  jvns          references
sqlite> .schema certs
CREATE TABLE IF NOT EXISTS "certs" ("id" integer primary key autoincrement,"created_at" datetime,"updated_at" datetime,"deleted_at" datetime,"jvn_id" integer,"title" varchar(255),"link" text );
CREATE INDEX idx_certs_deleted_at ON "certs"(deleted_at) ;
CREATE INDEX idx_certs_jvn_id ON "certs"(jvn_id) ;
sqlite> .headers ON
sqlite> .mode column
sqlite> SELECT * FROM certs;
```
> Collect US-CERT/JPCERT alerts from NVD/JVN feeds

- db/rdb.go
Fix a bug that not update LastModifiedData of feed_meta table in rdb.
> fix(meta): not update LastModifiedDate

- log/log.go
Fixes #153 
```panic: open /var/log/vuls/cve-dictionary.log: permission denied
goroutine 1 [running]:
github.com/inconshreveable/log15.must(...)
/home/ubuntu/go/pkg/mod/github.com/inconshreveable/log15@v0.0.0-20180818164646-67afb5ed74ec/handler.go:340
github.com/inconshreveable/log15.muster.FileHandler(0xc000240b00, 0x20, 0x19d76c0, 0x169aef0, 0x20, 0x0)
/home/ubuntu/go/pkg/mod/github.com/inconshreveable/log15@v0.0.0-20180818164646-67afb5ed74ec/handler.go:348 +0x8a
github.com/kotakanbe/go-cve-dictionary/log.SetLogger(0x15fa9c6, 0xd, 0x100)
/home/ubuntu/go/pkg/mod/github.com/kotakanbe/go-cve-dictionary@v0.4.1/log/log.go:40 +0x227
github.com/future-architect/vuls/commands.(*ReportCmd).Execute(0xc0000ee2a0, 0x19fd5a0, 0xc0000c2010, 0xc0000c8840, 0x0, 0x0, 0x0, 0x0) …
```
> fix(logger): panic if no file permission #153

- models/models.go
I fixed the bug that list subcommand displays incorrect result "Unknown".
```
+---------+------+------------+---------+---------+
| SOURCE  | YEAR |   STATUS   | FETCHED | LATEST  |
+---------+------+------------+---------+---------+
| Unknown |      | Up-to-Date | Unknown | Unknown |
| Unknown |      | Up-to-Date | Unknown | Unknown |
| Unknown |      | Up-to-Date | Unknown | Unknown |
| Unknown |      | Up-to-Date | Unknown | Unknown |
+---------+------+------------+---------+---------+
```
> fix(list): list subcommand displays "Unknown" 

- commands/fetchnvd.go
- config/config.go
- fetcher/nvd/json/nvd.go
CPE relate data in NVD JSON feed is too heavy. 
It costs over 2.5GB of memory to fetch and store into DB.
Vuls uses this CPE data only in CPE based scan mode. 
(CPE data never used in OVAL based scan)
I add a mode that does not collect CPE information.
Please delete options that are not relevant.
./go-cve-dictionary fetchnvd -ignore-cpe -last2y
> feat(fetchnvd): add light flg to ignore cpe releated data

- fetcher/fetcher.go
I fixed a bug that 'list' command fails when fetched feeds exceed 20.
```bash
vuls:~$ go-cve-dictionary list
INFO[10-07|10:56:17] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2005.meta
INFO[10-07|10:56:17] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2007.meta
INFO[10-07|10:56:17] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2002.meta
INFO[10-07|10:56:17] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2006.meta
INFO[10-07|10:56:17] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2009.meta
INFO[10-07|10:56:17] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2012.meta
INFO[10-07|10:56:17] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2017.meta
INFO[10-07|10:56:17] Fetching... …
```
> Make 'list' command works correctly when fetched feeds exceed 20.

- fetcher/nvd/json/nvd.go
- models/models.go
This PR enables `go-cve-dictionary` to store reference tags. 
These are stored as a string where each tag is separated by a comma.
> Store reference tags

- fetcher/jvn/xml/jvn.go
- fetcher/nvd/json/nvd.go
The rejected CVEs are detected in nvd and jvn when the fetch is executed.
There had unique signatures in the summary, which I used to detect them.
Signature in NVD is ** Reject **.
Signature in JVN is ** 未確定 **, ** サポート外 **, ** 削除 **.
Fixes Vuls issue https://github.com/future-architect/vuls/issues/511
- [*] Bug fix (non-breaking change which fixes an issue)
NVD include many rejected CVEs
** 削除 ** is included in JVN.
Rejected CVEs can't count in NVD because succeed to detect.
** 削除 ** is not included in JVN.
* https://github.com/future-architect/vuls/issues/511
> Detect reject CVE in nvd and jvn

- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/list.go
- commands/server.go
- log/log.go
- server/server.go
```
./go-cve-dictionary server
EROR[02-02|06:17:49] Failed to create a log file              err="open /var/log/vuls/cve-dictionary.log: permission denied"
INFO[02-02|06:17:50] Starting HTTP Server...
EROR[02-02|06:17:50] open /var/log/vuls/access.log: permission denied
```
```
./go-cve-dictionary server
EROR[02-02|07:13:47] Failed to create a log file              err="open /var/log/vuls/cve-dictionary.log: permission denied"
INFO[02-02|07:13:47] Starting HTTP Server...
EROR[02-02|07:13:47] Failed to create a log file: open /var/log/vuls/access.log: permission denied
INFO[02-02|07:13:47] Listening on 127.0.0.1:1323
____    __
/ __/___/ /  ___
/ _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.3.10-dev
High performance, minimalist Go web framework
https://echo.labstack.com …
```
> fix(server): start if no write permmision for logdir

- fetcher/jvn/xml/jvn.go
Fixes #180 
```
make build; and ./go-cve-dictionary fetchjvn -years -force 2020
GO111MODULE=off go get -u golang.org/x/lint/golint
golint github.com/kotakanbe/go-cve-dictionary github.com/kotakanbe/go-cve-dictionary/commands github.com/kotakanbe/go-cve-dictionary/config github.com/kotakanbe/go-cve-dictionary/db github.com/kotakanbe/go-cve-dictionary/fetcher github.com/kotakanbe/go-cve-dictionary/fetcher/jvn/xml github.com/kotakanbe/go-cve-dictionary/fetcher/nvd github.com/kotakanbe/go-cve-dictionary/fetcher/nvd/json github.com/kotakanbe/go-cve-dictionary/log github.com/kotakanbe/go-cve-dictionary/models github.com/kotakanbe/go-cve-dictionary/server github.com/kotakanbe/go-cve-dictionary/util
echo github.com/kotakanbe/go-cve-dictionary github.com/kotakanbe/go-cve-dictionary/commands …
```
> fix(jvn): only logging if invalid cpe format in JVN

- fetcher/nvd/json/nvd.go
- Use only US-CERT as CERT information.
- Stop scraping CERT title in NVD fetch process, because errors occurred frequently.
> Use only US-CERT as CERT information in NVD

- fetcher/nvd/json/nvd.go
// The redis-put-process overwrite without referring the last modified date.
// Sort so that recent-feed is the last element.
sort.Slice(results, func(i, j int) bool { return results[i].URL < results[j].URL })
```
ubuntu@dev  │tmp  curl -s https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz | gunzip | jq '.CVE_Items[] | select( .cve.CVE_data_meta.ID == "CVE-2021-29647" ) | .lastModifiedDate'
"2021-04-02T04:15Z"
ubuntu@dev  │tmp  curl -s https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz | gunzip | jq '.CVE_Items[] | select( .cve.CVE_data_meta.ID == "CVE-2021-29647" ) | .lastModifiedDate'
"2021-04-05T11:38Z"
ubuntu@dev  │tmp  curl -s https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz | gunzip | jq '.CVE_Items[] | select( .cve.CVE_data_meta.ID == …
```
> fix(fetch-nvd): prevent overwriting with old cve-details on redis

- .github/workflows/golangci.yml
- db/db.go
- db/db_test.go
In the previous implementations, only the following four items were used in CPE match.
- type, vendor, product, version
In order to enable more detailed comparison, I will change the fields other than the above to be used for CPE comparison.
Pass `make test`
> fix(cpe): cpe match logic

- db/db.go
- db/rdb.go
- db/rdb_test.go
- db/redis.go
- db/redis_test.go
- go.mod
- go.sum
- models/models.go
Data sources such as JVN is defined the country's specific software as `affected software list`.
In order to detect vulnerabilities in those software, JVN should also be used as a vulnerability DB for CPE scanning, with the aim of complementing the information in NVD.
However, JVN has the problem that affected `versions` is not defined in machine-readable format ;)
In order to minimize false positives, the following methods are used for detection.
- When the same vendor and product are defined in NVD and JVN, NVD will be used.
- When the same vendor and product are **not** defined in NVD, JVN is used.
All the CVEs detected by JVN is detected by the VENDOR and PRODUCT match. 
Note that versions are not compared, so there are false positives.
If you want to use only NVD information for …
> feat(cpe): Use JVN when NVD is not available in CPE scan

- fetcher/jvn/xml/jvn.go
- fetcher/nvd/json/nvd.go
~~Remove the goroutine speedup in convert, as it seems to have little effect on the complexity of the code.~~
~~I rewrote the goroutine in the convert part of NVD and JVN to a simple for. JVN is slower and NVD is faster, probably because JVN uses goroutine in the following part:`collectCertLinks` to access links.~~
~~https://github.com/MaineK00n/go-cve-dictionary/blob/c2acd34f77a7ab377701870885d706126e982c03/fetcher/jvn/xml/jvn.go#L301~~
~~Therefore, I changed only NVD to a simple for loop.~~
In convert, set the appropriate concurrency for goroutine.
// upstream/master: 21s
```console
$ go-cve-dictionary fetchnvd --last2y
INFO[07-15|09:23:24] Fetching... https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.meta 
INFO[07-15|09:23:28] Fetched... …
```
> feat(fetcher/nvd): control the concurrency when convert

- README.md
- commands/fetchjvn.go
- commands/fetchnvd.go
- config/config.go
- db/redis.go
Unlike RDBs, Redis does not lose old data. For users who do not want to be affected by old data remaining, it is possible to set a timeout deadline for keys using the Redis EXPIRE command.
```console
127.0.0.1:6379> TTL CVE#CVE-2021-37600
(integer) 70
127.0.0.1:6379> TTL CVE#C#CVE-2021-31999
(integer) 65
127.0.0.1:6379> TTL CVE#microsoft::windows_10
(integer) 70
127.0.0.1:6379> TTL CVE#Meta
(integer) 16
127.0.0.1:6379> keys CVE#*
(empty array)
```
***Is this ready for review?:*** YES  
- https://redis.io/commands/expire
> feat(redis): add expire option

- commands/fetchjvn.go
- commands/fetchnvd.go
- config/config.go
- fetcher/jvn/xml/jvn.go
- fetcher/nvd/json/nvd.go
Fixes #201 
First, it fills in the data in CpeBase by default.
Also, rename `light` to `full`, and use `fetchnvd` to save more CPE data to the DB only when `full` is enabled.
```console
$ go-cve-dictionary.master fetchnvd --last2y --dbpath=$(pwd)/cve.master.sqlite3
$ go-cve-dictionary.pr fetchnvd --last2y --dbpath=$(pwd)/cve.pr.sqlite3
$ ll cve.*.sqlite3 
-rw-r--r-- 1 mainek00n mainek00n 291M Aug 11 05:36 cve.master.sqlite3
-rw-r--r-- 1 mainek00n mainek00n 177M Aug 11 06:07 cve.pr.sqlite3
$ sqlite3 cve.master.sqlite3
sqlite> SELECT COUNT(id) FROM env_cpes;
232662
$ sqlite3 cve.pr.sqlite3
sqlite> SELECT COUNT(id) FROM env_cpes;
0
$ go-cve-dictionary.pr fetchnvd --last2y --full --dbpath=$(pwd)/cve.pr.sqlite3
$ ll cve.pr.sqlite3 
-rw-r--r-- 1 mainek00n mainek00n 291M Aug 11 06:14 …
```
> feat(fetch): fill in CpeBase by default and change the option name

- db/db.go
- db/db_test.go
- db/rdb.go
- db/redis.go
- models/models.go
When searching by CPE URI, items that do not have a CPE that matches the CPE URI used in the search will not be responded to.
Also, delete `CveDetail.CveIDSource` as it is not needed.
```console
// upstream/master
$ curl -H "Content-type: application/json" -X POST -d '{"name": "cpe:/o:titan:sf_rush_smart_band_firmware:1.12"}' http://127.0.0.1:1323/cpes | jq
[
{
"CveID": "CVE-2020-11539",
"CveIDSource": "NVD",
"Nvd": [
{
"CveID": "CVE-2020-11539",
"Cpes": [
{
"URI": "cpe:/o:titan:sf_rush_smart_band_firmware:1.12",
}
],
}
],
"Jvn": [
{
"CveID": "CVE-2020-11539",
"Cpes": [
{
"URI": "cpe:/o:d-link:dir-615_firmware",
],
},
{
"CveID": "CVE-2020-11539",
"Cpes": [
{
"URI": "cpe:/o:titan:sf_rush_smart_band_firmware",
}
],
}
]
}
]
// PR
$ curl -H "Content-type: application/json" -X POST -d …
```
> feat(db): filter contents of CveDetail by CPE URI

- db/rdb.go
[future-architect/vuls](https://github.com/future-architect/vuls) is reporting `too many SQL variables` error.
In order to avoid this, the EnvCpes part of the NVD is obtained with a for loop.
From the survey of the https://github.com/future-architect/vuls/issues/1295#issuecomment-909415220, the suspicious part seems to be the query that fills `nvd_env_cpes` when searching for CVE-2017-5715.
However, in go-cve-dictionary server mode, CVE-2017-5715 terminates successfully and a response is obtained.
```console
$ go-cve-dictionary server
{"time":"2021-09-01T05:14:24.68800381+09:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:1323","method":"GET","uri":"/cves/CVE-2017-5715","user_agent":"curl/7.68.0","status":200,"error":"","latency":55261926,"latency_human":"55.261926ms","bytes_in":0,"b …
```
> fix(rdb): avoid too many SQL variables

- db/db.go
- db/db_test.go
- db/rdb.go
- fetcher/jvn/jvn.go
- fetcher/nvd/nvd.go
- fetcher/nvd/util.go
- go.mod
- go.sum
- models/models.go
fixes #208 
https://nvd.nist.gov/vuln/data-feeds#JSON_FEED
In the JSON feed of the NVD, the information of the CPE corresponding to a certain CVE-ID is defined as follows.
"ID" : "CVE-2018-0733",
```
"configurations" : {
"CVE_data_version" : "4.0",
"nodes" : [ {
"operator" : "OR",
"cpe_match" : [ {
"vulnerable" : true,
"cpe23Uri" : "cpe:2.3:a:openssl:openssl:*:*:*:*:*:*:*:*",
"versionStartIncluding" : "1.1.0",
"versionEndIncluding" : "1.1.0g"
} ]
} ]
},
```
There are many well-known software packages that use non-semantic versioning, such as OpenSSL.
In the previous implementation, the comparison process failed when the version range was not in Semantic versioning format.
There was a problem of undetectability if it is not semantic versioning.
So, it is better that compared and processed …
> feat(cpematch): rpm match if version range defined in NVD is not semver style

- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- db/db.go
- db/rdb.go
- db/redis.go
- fetcher/jvn/jvn.go
- fetcher/jvn/jvn_test.go
- fetcher/nvd/nvd.go
- fetcher/nvd/nvd_test.go
- fetcher/nvd/util.go
- fetcher/nvd/util_test.go
- models/models.go
CVEs of "recent" and "modified" that were always brought at fetch time were duplicated with CVEs of years.
In the case of RDB, multiple CVEs were inserted, and multiple identical ones appeared in the response. Also, in the case of Redis, the data was overwritten, and old data may have appeared in the response.
```console
$ go-cve-dictionary.old fetch nvd --years 2021 --dbpath ./cve.old.sqlite
$ go-cve-dictionary.new fetch nvd --years 2021 --dbpath ./cve.new.sqlite
$ go-cve-dictionary.old server --dbpath ./cve.old.sqlite --port 1325
$ go-cve-dictionary.new server --dbpath ./cve.new.sqlite --port 1326
// upstream/master
$ curl http://127.0.0.1:1326/cves/CVE-2020-20349 | jq | grep "CveID"
"CveID": "CVE-2020-20349",
"CveID": "CVE-2020-20349",
"CveID": "CVE-2020-20349",
// PR
$ curl …
```
> fix: remove duplicate cves

- commands/fetchjvn.go
- commands/fetchnvd.go
If an error occurs during the first fetch, it is required to clean the DB during the second Insert. 
The old data can be deleted when updating between the same schema versions.
To avoid this problem, insert FetchMeta first.
> fix(db): change fetchmeta insert order

- commands/fetch.go
- fetcher/fetcher.go
- fetcher/nvd/nvd.go
- go.mod
- go.sum
In some environments, it seems that the following error occurs and the NVD cannot be fetched.
So, Implemented retry on error.
```
Failed to FetchConvert. err: Failed to fetch. err: Failed to fetch. err: Failed to fetch file. err: aborting: could not write to output stream: Get "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2006.json.gz": dial tcp 54.85.30.225:443: connect: operation timed out
```
Complete fetches while retrying on error.
```
08:13 ≡ go-cve-dictionary fetch nvd  --log-json --dbtype redis --dbpath redis://localhost/0
{"lvl":"info","msg":"Inserting NVD into DB (redis).","t":"2021-09-24T08:14:21.179141+09:00"}
{"lvl":"info","msg":"Fetching CVE information from NVD(recent, modified).","t":"2021-09-24T08:14:21.17926+09:00"}
{"lvl":"info","msg":"Fetching... …
```
> fix(fetch): not to use htcat, use backoff retry, set user-agent as curl

- db/rdb.go
- db/redis.go
- fetcher/nvd/nvd.go
Use the pipeline in GetMulti in Redis, and use GetMulti as much as possible when searching CPE.
Also, do not unnecessarily judge ErrRecordNotFound in the RDB.
```console
$ make clean-integration && make build-integration
$ make fetch-rdb && make fetch-redis
$ make diff-server-rdb && make diff-server-redis && make diff-server-rdb-redis
```
> refactor(db): return pipeline in Redis GetMulti and do not judge ErrRecordNotFound unnecessarily

- commands/fetch.go
- db/redis.go
Expire was introduced to ensure safe operation in Redis, but since expire can only be set per key, it is not very useful for Sets and Hash.
Therefore, if there is any old content in each fetch, it will be deleted.
***Is this ready for review?:*** NO
> breaking-change(redis): deprecated expire option

- .github/workflows/golangci.yml
- .golangci.yml
- .goreleaser.yml
- .revive.toml
- GNUmakefile
- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- db/rdb.go
- db/redis.go
Change the linter to revive, since golint has been deprecated as follows.
> NOTE: Golint is deprecated and frozen. There's no drop-in replacement for it, but tools such as Staticcheck and go vet should be used instead.
```console
$ make lint
$ golangci-lint run -c .golangci.yml
```
> chore(linter): change linter from golint to revive

- fetcher/jvn/jvn.go
Change the format of the CVE-ID so that it will not be registered if it does not match the format of the CVE-ID(`^CVE-[0-9]{4}-[0-9]{4,}$`).
Fixes #229 
The ones that disappear in diff are the ones that are not suitable for the format (e.g. "CVE-CVE-xxxx-xxxx", "CCVE-xxxx-xxxx", "xxxx-xxxx"), or because a space has been added, so that there are now two registered items. ( e.g. "CVE-xxxx-xxxx", "CVE-xxxx-xxxx ")
The reason for the addition in diff is that the CVE-IDs that used to only have the form of CVE-ID with spaces are now CVE-IDs with spaces removed. (master: "CVE-xxxx-xxxx " → PR: "CVE-xxxx-xxxx")
Translated with www.DeepL.com/Translator (free version)
```console
$ go-cve-dictionary.master fetch jvn --dbpath master.sqlite3
$ sqlite3 master.sqlite3
sqlite> .output master.txt
sqlite> …
```
> fix(fetcher/jvn): not register invalid CVE-ID

- db/db.go
- fetcher/jvn/jvn.go
- fetcher/jvn/jvn_test.go
Logging when a invalid CVEID is found.
refs. https://github.com/vulsio/go-cve-dictionary/pull/233
```console
$ go-cve-dictionary fetch jvn
...
WARN[12-28|12:04:14] Failed to get CVE-ID. Invalid CVE-ID: CCVE-2021-20208 
INFO[12-28|12:04:14] Inserting fetched CVEs(2021)... 
5544 / 5544 [-------------------------------------------------] 100.00% 2876 p/s
INFO[12-28|12:04:17] Refreshed 5544 CVEs. 
INFO[12-28|12:04:17] Finished fetching JVN.
```
> chore(fetch/jvn): logging when invalid CVE-ID is found

- README.md
- commands/fetchjvn.go
- commands/fetchnvd.go
- db/db.go
- db/rdb.go
- db/redis.go
Due to a change at https://github.com/vulsio/go-cve-dictionary/pull/214, go-cve-dictionary could no longer select a year to fetch.
However, if all the years were to be fetched, the DB size would become too large, and there would be a demand for only certain years, etc., so I added the ability to select and fetch years.
Fixes #231 
If you selected years in the previous fetch command, they were added to the DB, but the current fetch command will recreate a new DB with only the selected years. 
```console
$ go-cve-dictionary fetch nvd --years 2020
$ sqlite3 cve.sqlite3
sqlite> SELECT * FROM nvds LIMIT 3;
id|feed_meta_id|cve_id|published_date|last_modified_date
1|1|CVE-2020-0003|2020-01-08 19:15:00+00:00|2020-01-29 21:15:00+00:00
2|1|CVE-2020-0002|2020-01-08 19:15:00+00:00|2021-07-21 …
```
> feat(fetch): fetch by year

- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- db/rdb.go
- db/redis.go
- models/models.go
Add the time when the fetch is completed to fetchmeta.
```console
$ go-cve-dictionary fetch nvd
$ sqlite3 cve.sqlite3  
sqlite> SELECT last_fetched_at FROM fetch_meta;
2021-12-26 08:45:48.769925148+09:00
$ go-cve-dictionary fetch nvd
$ sqlite3 cve.sqlite3  
sqlite> SELECT last_fetched_at FROM fetch_meta;
2021-12-26 08:50:40.68298214+09:00
```
```console
$ redis-cli -p 6379
127.0.0.1:6379> HGET CVE#FETCHMETA LastFetchedAt
(nil)
$ go-cve-dictionary fetch nvd --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ redis-cli -p 6379
127.0.0.1:6379> HGET CVE#FETCHMETA LastFetchedAt
"2021-12-26T08:52:51.973265483+09:00"
$ go-cve-dictionary fetch nvd --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ redis-cli -p 6379
127.0.0.1:6379> HGET CVE#FETCHMETA LastFetchedAt …
```
> feat(db): add LastFetchedDate in fetchmeta

- db/db.go
- db/db_test.go
```
{
name: "true: NA should match all version",
uri:  "cpe:/h:fortinet:fortigate-100d:v6.2.9",
cpe: models.CpeBase{
URI: "cpe:/h:fortinet:fortigate-100d:-",
},
wantIsExactVerMatch:      true,
wantIsRoughVerMatch:      false,
wantIsVendorProductMatch: false,
},
```
> fix(cpescan): match if affected version is NA

- .github/workflows/fetch.yml
- README.md
- commands/fetchfortinet.go
- commands/server.go
- db/db.go
- db/db_test.go
- db/rdb.go
- db/redis.go
- fetcher/fetcher.go
- fetcher/fortinet/fortinet.go
- fetcher/fortinet/types.go
- models/models.go
- server/server.go
new support for fortinet data feed
```console
// terminal 1
$ go-cve-dictionary fetch fortinet
INFO[09-20|22:38:18] Fetching... https://github.com/vulsio/vuls-data-raw-fortinet/archive/refs/heads/main.zip 
INFO[09-20|22:38:20] Inserting Fortinet into DB (sqlite3). 
INFO[09-20|22:38:20] Deleting Fortinet tables... 
INFO[09-20|22:38:20] Inserting fetched 822 CVEs... 
822 / 822 [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% ? p/s
INFO[09-20|22:38:20] Refreshed 822 CVEs. 
INFO[09-20|22:38:20] Finished fetching Fortinet.
$ go-cve-dictionary server
// terminal 2
$ curl -s http://127.0.0.1:1323/cves/CVE-2023-33306 | jq "."
{
"CveID": …
```
> feat(fortinet): new support for fortinet data feed

- README.md
- commands/fetch.go
- fetcher/fetcher.go
- fetcher/jvn/jvn.go
Fixes #334
I execute that in docker.
```bash
$ docker build . -t temp
$ docker run --rm -it     -v $PWD:/go-cve-dictionary     temp fetch jvn --without-jvncert
INFO[09-08|23:40:35] Inserting JVN into DB (sqlite3). 
...
INFO[09-08|23:42:21] Finished fetching JVN. 
```
> feat(fetch-jvn): add without-jvncert option

- README.md
- commands/fetch.go
- commands/fetchjvn.go
`--without-jvncert` added by #335 is a flag that can only be used with JVN command. Therefore, it should be a flag limited to JVN command.
```console
$ go-cve-dictionary fetch -h
Fetch Vulnerability dictionary
Usage:
go-cve-dictionary fetch [command]
Available Commands:
fortinet    Fetch Vulnerability dictionary from Fortinet Advisories
jvn         Fetch Vulnerability dictionary from JVN
nvd         Fetch Vulnerability dictionary from NVD
Flags:
--batch-size int    The number of batch size to insert. (default 5)
-h, --help              help for fetch
--without-jvncert   not request to jvn cert (only jvn).
Global Flags:
...
```
```console
$ go-cve-dictionary fetch -h
Fetch Vulnerability dictionary
Usage:
go-cve-dictionary fetch [command]
Available Commands:
fortinet    Fetch Vulnerability …
```
> chore(command): --without-jvncert flag limited to jvn command

- fetcher/nvd/nvd.go
- models/models.go
add source, type field
```console
$ go-cve-dictionary server
$ curl -s http://127.0.0.1:1323/cves/CVE-2023-1194 | jq "."
{
"CveID": "CVE-2023-1194",
"Nvds": [
{
"CveID": "CVE-2023-1194",
"Descriptions": [
{
"Lang": "en",
"Value": "An out-of-bounds (OOB) memory read flaw was found in parse_lease_state in the KSMBD implementation of the in-kernel samba server and CIFS in the Linux kernel. When an attacker sends the CREATE command with a malformed payload to KSMBD, due to a missing check of `NameOffset` in the `parse_lease_state()` function, the `create_context` object can access invalid memory."
},
{
"Lang": "es",
"Value": "Se encontró una falla de lectura de memoria Out-Of-Bounds (OOB) en parse_lease_state en la implementación KSMBD del servidor samba en el kernel y CIFS en el kernel de …
```
> feat(nvd): add source, type field

- fetcher/fortinet/fortinet.go
- fetcher/fortinet/types.go
`go-cve-dictionary fetch fortinet` was not collecting all the CPEs listed in the advisory. 
This PR fixes this bug here.
```console
$ go-cve-dictionary fetch fortinet
$ sqlite3 cve.sqlite3 "SELECT fortinets.advisory_id, fortinets.cve_id,fortinet_cpes.formatted_string, fortinet_cpes.version_start_excluding,fortinet_cpes.version_start_including,fortinet_cpes.version_end_excluding, fortinet_cpes.version_end_including FROM fortinets JOIN fortinet_cpes ON fortinets.id == fortinet_cpes.fortinet_id WHERE fortinets.advisory_id = 'FG-IR-23-001'" | sort
FG-IR-23-001|CVE-2023-25610|cpe:2.3:h:fortinet:fortigate-100d:-:*:*:*:*:*:*:*||||
FG-IR-23-001|CVE-2023-25610|cpe:2.3:h:fortinet:fortigate-200c:-:*:*:*:*:*:*:*||||
FG-IR-23-001|CVE-2023-25610|cpe:2.3:h:fortinet:fortigate-200d:-:*:*:*:*:*:*:*|||| …
```
> fix(fetch/fortinet): collect all CPEs

- db/db.go
- db/rdb.go
- db/redis.go
- server/server.go
This PR allows you to obtain the CVE ID list registered in the DB.
```console
$ curl http://127.0.0.1:1323/cves/ids
["CVE-2023-21043","CVE-2023-37256", ... ,"CVE-2023-46765"]
$ curl -X POST  -H "Content-Type: application/json" --data '["CVE-2023-0706", "CVE-2023-2569"]' http://127.0.0.1:1323/cves | jq
{
"CVE-2023-0706": {
"CveID": "CVE-2023-0706",
"Nvds": [
{
"CveID": "CVE-2023-0706",
"Descriptions": [
{
"Lang": "en",
"Value": "A vulnerability, which was classified as critical, has been found in SourceCodester Medical Certificate Generator App 1.0. Affected by this issue is some unknown functionality of the file manage_record.php. The manipulation of the argument id leads to sql injection. The attack may be launched remotely. The identifier of this vulnerability is VDB-220340."
}
], …
```
> feat(db,server): add GetCveIDs

- README.md
- commands/search.go
Until now, the ability to search within the DB was only provided through the go-cve-dictionary server.
Therefore, in this PR, we will create a search command that searches within the DB without a server.
```console
$ go-cve-dictionary search cve
[
"CVE-2023-38624",
"CVE-2024-20750",
"CVE-2024-21101",
"CVE-2023-27427",
"CVE-2023-30445",
...
$ go-cve-dictionary search cve CVE-2024-3400
{
"CveID": "CVE-2024-3400",
"Nvds": [
{
"CveID": "CVE-2024-3400",
"Descriptions": [
{
"Lang": "en",
"Value": "A command injection as a result of arbitrary file creation vulnerability in the GlobalProtect feature of Palo Alto Networks PAN-OS software for specific PAN-OS versions and distinct feature configurations may enable an unauthenticated attacker to execute arbitrary code with root privileges on the …
```
> feat(commands): add search command

- db/rdb.go
- db/redis.go
The first CVE was created in 1999, the previous feed fetch only contained CVE from 2002 onward. But with the API we get the CVE from 1999, 2000 and 2001
```console
$ go-cve-dictionary fetch nvd
INFO[04-24|19:46:22] Inserting NVD into DB (sqlite3). 
INFO[04-24|19:46:22] Deleting NVD tables... 
INFO[04-24|19:46:22] Fetching CVE information from NVD. 
INFO[04-24|19:46:22] Fetching... https://github.com/vulsio/vuls-data-raw-nvd-api-cve/archive/refs/heads/main.tar.gz 
INFO[04-24|19:46:41] Fetching CVE information from NVD(2002). 
INFO[04-24|19:46:42] Inserting fetched CVEs(2002)... 
2392 / 2392 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1270 p/s …
```
> fix(fetch): fix first CVE year

- fetcher/nvd/nvd.go
Previous data feeds did not include a status, but the data feeds we currently use include a status.
Therefore, there is no need to determine the reject status from the description.
https://nvd.nist.gov/vuln/vulnerability-status#divNvdStatus
e.g. 
previous data feed: 
https://github.com/vulsio/vuls-data-raw-nvd-feed-cve/blob/6c059524140e52c3bcfd21b209c83e81450ffafb/2024/CVE-2024-25001.json
https://github.com/vulsio/vuls-data-raw-nvd-feed-cve/blob/6c059524140e52c3bcfd21b209c83e81450ffafb/2024/CVE-2024-35941.json
currently data feeds:
https://github.com/vulsio/vuls-data-raw-nvd-api-cve/blob/acb7222b9e1521aabef89172f54ce02770e2cbe2/2024/CVE-2024-25001.json
https://github.com/vulsio/vuls-data-raw-nvd-api-cve/blob/acb7222b9e1521aabef89172f54ce02770e2cbe2/2024/CVE-2024-35941.json
```console
$ …
```
> feat(fetcher/nvd): update reject cve logic

- .github/workflows/fetch.yml
- README.md
- commands/fetchfortinet.go
- commands/fetchjvn.go
- commands/fetchmitre.go
- commands/fetchnvd.go
- commands/root.go
- commands/search.go
- commands/server.go
- commands/version.go
- db/db.go
- db/rdb.go
- db/redis.go
- fetcher/jvn/jvn.go
- fetcher/mitre/mitre.go
- fetcher/mitre/types.go
- fetcher/nvd/nvd.go
- models/models.go
- models/models_test.go
Fixes #287, #351
```console
$ go-cve-dictionary fetch mitre
$ go-cve-dictionary search cve
[
"CVE-2021-34564",
"CVE-2023-30720",
"CVE-2015-0434",
...
$ go-cve-dictionary search cve CVE-2024-5732
{
"CveID": "CVE-2024-5732",
"Nvds": [],
"Jvns": [],
"Fortinets": [],
"Mitres": [
{
"DataType": "",
"DataVersion": "",
"CVEMetadata": {
"CVEID": "CVE-2024-5732",
"AssignerOrgID": "1af790b2-7ee1-4545-860a-a788eba489b5",
"AssignerShortName": "VulDB",
"RequesterUserID": null,
"Serial": null,
"State": "PUBLISHED",
"DatePublished": "2024-06-07T10:00:04.02Z",
"DateUpdated": "2024-06-07T14:50:46.944Z",
"DateReserved": "2024-06-07T05:12:19.233Z",
"DateRejected": null
},
"Containers": [
{
"ContainerType": "CNA", …
```
> feat(mitre): add new datasource: mitre

- db/rdb.go
- fetcher/nvd/nvd.go
- fetcher/nvd/types.go
- models/models.go
support NVD CVSS v4.0 schema
```console
$ go-cve-dictionary fetch nvd 2024
$ go-cve-dictionary search cve CVE-2024-5732
{
"CveID": "CVE-2024-5732",
"Nvds": [
{
"CveID": "CVE-2024-5732",
"Descriptions": [
{
"Lang": "en",
"Value": "A vulnerability was found in Clash up to 0.20.1 on Windows. It has been declared as critical. This vulnerability affects unknown code of the component Proxy Port. The manipulation leads to improper authentication. The attack can be initiated remotely. The exploit has been disclosed to the public and may be used. It is recommended to change the configuration settings. VDB-267406 is the identifier assigned to this vulnerability."
},
{
"Lang": "es",
"Value": "Se encontró una …
```
> feat(nvd): support CVSS v4.0

- db/rdb.go
- fetcher/mitre/mitre.go
- models/models.go
fill DataType, DataVersion, affected
```console
$ go-cve-dictionary fetch mitre 2024
$ go-cve-dictionary search cve CVE-2024-5732
{
"CveID": "CVE-2024-5732",
"Nvds": [],
"Jvns": [],
"Fortinets": [],
"Mitres": [
{
"DataType": "",
"DataVersion": "",
"CVEMetadata": {
"CVEID": "CVE-2024-5732",
"AssignerOrgID": "1af790b2-7ee1-4545-860a-a788eba489b5",
"AssignerShortName": "VulDB",
"RequesterUserID": null,
"Serial": null,
"State": "PUBLISHED",
"DatePublished": "2024-06-07T10:00:04.02Z",
"DateUpdated": "2024-06-07T14:50:46.944Z",
"DateReserved": "2024-06-07T05:12:19.233Z",
"DateRejected": null
},
"Containers": [
{
"ContainerType": "CNA",
"ProviderMetadata": {
"OrgID": "1af790b2-7ee1-4545-860a-a788eba489b5", …
```
> feat(mitre): fill DataType, DataVersion, affected

- commands/search.go
- db/db.go
- db/rdb.go
- db/redis.go
- server/server.go
select advisories and related cve ids
```console
$ go-cve-dictionary fetch jvn 2024
$ go-cve-dictionary search advisories jvn
{
"JVNDB-2024-000001": [
"CVE-2024-22027"
],
"JVNDB-2024-000002": [
"CVE-2024-22028"
],
"JVNDB-2024-000003": [
"CVE-2024-21584"
],
...
$ docker run --rm --name redis -d -p 127.0.0.1:6379:6379 redis
$ go-cve-dictionary fetch jvn 2024 --dbtype redis --dbpath "redis://127.0.0.1:6379/1"
$ go-cve-dictionary search advisories jvn --dbtype redis --dbpath "redis://127.0.0.1:6379/1"
{
"JVNDB-2024-000001": [
"CVE-2024-22027"
],
"JVNDB-2024-000002": [
"CVE-2024-22028"
],
"JVNDB-2024-000003": [
"CVE-2024-21584"
],
...
```
***Is this ready for …
> feat: select advisories

- db/redis.go
When checking the CVEID in the DB with Redis, the Key Prefix was still attached, so this PR removes it.
```console
$ go-cve-dictionary fetch fortinet
$ go-cve-dictionary search cve
[
"CVE-2020-6643",
"CVE-2020-11901",
"CVE-2022-26122",
"CVE-2023-47536",
"CVE-2015-1792",
"CVE-2017-3730",
"CVE-2019-15710",
"CVE-2023-27995",
"CVE-2023-34988",
"CVE-2015-3620",
"CVE-2018-1354",
...
```
```console
$ docker run --rm --name redis -d -p 127.0.0.1:6379:6379 redis
$ go-cve-dictionary fetch fortinet --dbtype "redis" --dbpath "redis://127.0.0.1:6379"
$ go-cve-dictionary search cve --dbtype "redis" --dbpath "redis://127.0.0.1:6379"
[
"CVE#CVE#CVE-2017-1000250",
"CVE#CVE#CVE-2021-24014",
"CVE#CVE#CVE-2022-29055", …
```
> fix(db/redis): remove CVE key prefix

- fetcher/cisco/cisco_test.go
Cisco products are generated in parallel and the order is not guaranteed, which causes the test to fail as follows:
https://github.com/vulsio/go-cve-dictionary/blob/24d381399187368be6ce9358878b884b89fc9ad4/fetcher/cisco/cisco.go#L191-L243
https://github.com/vulsio/go-cve-dictionary/actions/runs/15774861396/job/44466880874?pr=459
Therefore, when comparing in tests, we sort and compare Cisco products.
```console
$ for i in {1..100}; do go test -count 1 -cover -v ./fetcher/cisco/ -run 'Test_convert/cisco-sa-snmp-dos-sdxnSUcW' 2>&1 >/dev/null; echo $? ; done | sort | uniq -c
76 0
24 1
```
```console
$ for i in {1..100}; do go test -count 1 -cover -v ./fetcher/cisco/ -run 'Test_convert/cisco-sa-snmp-dos-sdxnSUcW' …
```
> test(fetcher/cisco): fix test comparison by sorting cisco products
