- server/server.go
follow labstack/echo changes "from" to "with"
> follow https://github.com/labstack/echo/commit/1a7bc67

- nvd/nvd.go
> Fix invalid memory access while fetching data from NVD. #5

- README.md
- commands/fetchjvn.go
- commands/fetchnvd.go
- nvd/nvd.go
https://github.com/future-architect/vuls/issues/39
> Add http proxy support, Fix NVD URL, Fix Error handling of goroutine

- models/models.go
Add xml:"-" to Gorm's meta struct fields defined in models/model.go
refer to https://github.com/future-architect/vuls/pull/240
> add struct tag for encoding/xml

- db/db.go
- main.go
fix a GORM sqlite dialect import.
ex. http://jinzhu.me/gorm/database.html#connecting-to-a-database
> fix GORM import for sqlite3.

- README.md
- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- log/log.go
- server/server.go
- util/util.go
see #26
see https://github.com/future-architect/vuls/pull/301
> Add -log-dir flag

- GNUmakefile
- commands/fetchnvd.go
- commands/server.go
- lock.json
- models/models.go
- Remove unnecessary func
- Add depup target in Makefile
- update dependencies
> Remove unnecessary func

- README.md
- commands/fetchnvd.go
- commands/server.go
https://github.com/future-architect/vuls/pull/296#issuecomment-274411324
1. gofmt
https://github.com/kotakanbe/go-cve-dictionary/compare/master...galigalikun:update-readme?expand=1#diff-4b93e352f742fd546d9ba3a836d8cfe1L10
2. back quotes
https://golang.org/ref/spec#String_literals
https://github.com/kotakanbe/go-cve-dictionary/compare/master...galigalikun:update-readme?expand=1#diff-69bd0a9ddb65669d220b124fc5a3ed80L114
> update readme help

- db/rdb.go
- db/redis.go
I fixed nil pointer access in Get() method.
> #59 fix nil pointer access

- db/redis.go
add redis's key prefix to jvn.
> fix redis jvn prefix

- README.md
- add comments for -log-dir option
- fix section hierarchy
- remove trailing spaces
- some fix for markdownlint
- some misspelling fixed
> improve README documentation.

- Gopkg.lock
- Gopkg.toml
- server/server.go
hi!
Im adapted because the Echo version has gone up and the interface has changed.
> update echo to 3.2.1

- db/rdb.go
- db/redis.go
fix output quiet when fetching nvd.
> fix output quiet

- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- db/db.go
- db/rdb.go
- db/redis.go
* add newdb function
* add cloedb function
* fix golint (redis.Z)
> add newdb and closedb

- commands/fetchjvn.go
- commands/fetchnvd.go
I found a typo. Please consider to marge.
> fix typo: inert -> insert

- commands/fetchnvd.go
- nvd/nvd.go
We will only retrieve information for the past 8 days.
> Added "-modified" option to fetchnvd command

- db/db.go
- db/rdb.go
- db/redis.go
I want get mulit cvedetail at once.
So, I added a method of `GetMulti` in redis driver.
> add multi get in redis

- db/redis.go
fixed bug of the function `getMulti` in redis db.
> fix multi get

- db/db.go
- jvn/jvn.go
temporary solution
V3 support will be done early in March.
> fix: support JVN new shcema, ignore CVSS v3 for now

- GNUmakefile
- Gopkg.lock
- Gopkg.toml
- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/server.go
- config/config.go
- db/db.go
- db/rdb.go
- db/redis.go
- jvn/jvn.go
- log/log.go
- nvd/nvd.go
- server/server.go
- util/util.go
Unable to merge to nvd-json because the dev branch has so many changes.
Reverts kotakanbe/go-cve-dictionary#86
> Revert "change log package"

- db/rdb.go
- db/redis.go
change cpe match log lvl to warn
> change unmatch cpe log to warn

- Gopkg.lock
> fix(dep): failed to fetch labstack/echo during `make install` #118

- db/db.go
- db/db_test.go
see https://github.com/future-architect/vuls/issues/789
> fix(cpe): dismiss when the CPE in NVD isn't the semver format

- db/db.go
- db/db_test.go
- db/rdb.go
- db/redis.go
see https://github.com/future-architect/vuls/issues/793
> fix(cpe): cpe matching bug 

- db/db.go
Change to not refer to NvdJSON containing nil
> debug cpe match

- db/rdb.go
- fetcher/jvn/xml/jvn.go
- fetcher/nvd/json/nvd.go
> fix(nvd): nil pointer while fetchnvd --years 2002

- commands/fetchnvd.go
- config/config.go
- db/rdb.go
- fetcher/nvd/json/nvd.go
Even if there are no updates in Feed,  it will fetch and update.
For example, after fetching with -light, if you want to get CPE, you can fetch feeds again with -force.
> Add a -force flag to fetchnvd

- commands/fetchjvn.go
- db/rdb.go
- fetcher/jvn/xml/jvn.go
> feat(jvn): add -light -force flags to fetchjvn

- db/rdb.go
- db/redis.go
I removed log output of `Opening DB.` and `Migrating DB.`
> remove log of opening and migrating db

- commands/fetchjvn.go
- commands/fetchnvd.go
- commands/list.go
- commands/server.go
- log/log.go
- add -log-to-file
- don't output to file by default
> feat(logging): add -log-to-file and don't output to file by default

- db/db.go
- db/rdb.go
- db/redis.go
- db/redis_test.go
- models/models.go
- models/models_test.go
- server/server.go
Fixes `HasJvn` and `HasNvd`.
refs. https://github.com/future-architect/vuls/pull/1273
Test cases were written and `make test` was performed.
- https://github.com/future-architect/vuls/pull/1273
> fix(GetCveIDsByCpeURI): remove Nvd for Jvn-match, and remove Jvn for Nvd-Match in CveDetail

- db/db.go
- db/db_test.go
Fixed because it was not implemented in filterCveDetailByCpeURI.
> fix: If the same affected product deifned in NVD and JVN, ignore JVN

- fetcher/fetcher.go
- fetcher/jvn/jvn.go
- fetcher/nvd/nvd.go
```
EROR[09-17|08:49:50] Failed to insert. dbpath: /home/ubuntu/go/src/github.com/vulsio/go-cve-dictionary/integration/cve.old.sqlite3, err: Failed to FetchConvert. err: Failed to fetch. err: Failed to fetch. err: [aborting: could not write to output stream: Expected HTTP Status 200, received: "403 Forbidden"] 
Failed to FetchConvert. err: Failed to fetch. err: Failed to fetch. err: [aborting: could not write to output stream: Expected HTTP Status 200, received: "403 Forbidden"]
GNUmakefile:94: recipe for target 'fetch-rdb' failed
make: *** [fetch-rdb] Error 1
```
No difference was found in the diff test.
> fix(fetch-nvd): fix 403 Forbidden

- commands/fetchjvn.go
- commands/fetchnvd.go
- db/db.go
- db/rdb.go
- db/redis.go
- fetcher/jvn/jvn.go
- fetcher/nvd/nvd.go
- models/models.go
- models/models_test.go
FeedMeta is no longer needed, so it is removed.
```console
$ go-cve-dictionary fetch nvd
$ go-cve-dictionary fetch jvn
$ go-cve-dictionary fetch nvd --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ go-cve-dictionary fetch jvn --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
```
> feat(models): remove FeedMeta

- db/redis.go
Limit to `CVE#` prefix, not randomkey.
> fix(redis): change IsGoCVEDictModelV1

- .github/workflows/docker-build.yml
Add arm64 image using docker's multi platform build feature.
ref: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
***Is this ready for review?:*** YES  
* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/
> feat: support arm64

- .github/workflows/goreleaser.yml
> fix(ci): remove unnecessary step

- Dockerfile
Starting with v0.12.0, git is required, but git was not installed in the official Docker image. Therefore, add git.
```console
$ docker build -t vuls/go-cve-dictionary -f ./Dockerfile .
$ docker run --rm vuls/go-cve-dictionary:latest fetch nvd
```
> fix(docker): add git package

- fetcher/fetcher.go
remove TLS InsecureSkipVerify
```
// InsecureSkipVerify controls whether a client verifies the server's
// certificate chain and host name. If InsecureSkipVerify is true, crypto/tls
// accepts any certificate presented by the server and any host name in that
// certificate. In this mode, TLS is susceptible to machine-in-the-middle
// attacks unless custom verification is used. This should be used only for
// testing or in combination with VerifyConnection or VerifyPeerCertificate.
InsecureSkipVerify bool
```
Please delete options that are not relevant.
by CI
> feat(fetcher): remove TLS InsecureSkipVerify
